# Events Data Analysis

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
BASE_DIR = "C:\\Users\\VishwasKSingh\\Workspace\\kantar-workspace-1\\my_project\\data\\"

In [3]:
registrations_df = pd.read_csv(BASE_DIR+"registrations.csv")

In [5]:
pricing_df = pd.read_csv(BASE_DIR+"pricing.csv")
events_df = pd.read_csv(BASE_DIR+"events.csv")
channels_df = pd.read_csv(BASE_DIR+"channels.csv")

In [6]:
attendees_df = pd.read_json(BASE_DIR+"attendees.json")

In [7]:
registrations_df.head()

,reg_id,event_id,attendee_email,reg_timestamp,payment_status,ticket_type
0,RE001000,E001,user0@example.com,2025-12-31 10:00,paid,earlybird
1,RE001001,E001,user1@example.com,2025-12-18 10:00,cancelled,standard
2,RE001002,E001,user2@example.com,2025-12-23 10:00,pending,student
3,RE001003,E001,user3@example.com,2026-01-11 10:00,paid,student
4,RE001004,E001,user4@example.com,2025-12-14 10:00,pending,standard

In [8]:
channels_df.head()

  event_id  channel  spend  impressions
0     E001    email   7000        35000
1     E001   social   5000        10000
2     E001  partner   7000        20000
3     E002    email   5000        35000
4     E002   social   5000        10000

In [9]:
pricing_df.head()

  event_id  base_price discount_code  discount_pct currency
0     E001        3000     STUDENT15            15      INR
1     E002        3000       EARLY10            10      INR
2     E003        3000          NY25            25      INR
3     E004        3000          NY25            25      INR
4     E005        2000           NaN             0      INR

In [10]:
events_df.head()

,event_id,topic,city,venue_capacity,scheduled_date_time,instructor_id
0,E001,Python OOP,Bengaluru,50,2026-01-13 10:00,I001
1,E002,Data Wrangling,Bengaluru,30,2026-01-16 14:00,I001
2,E003,Python OOP,Bengaluru,40,2026-01-19 10:00,I003
3,E004,Python OOP,Mysuru,60,2026-01-22 10:00,I002
4,E005,Machine Learning Essentials,Bengaluru,40,2026-01-25 14:00,I002

In [11]:
attendees_df.head()

,attendee_email,company,role,city,industry,notes
0,user0@example.com,Contoso,Student,Pune,IT,Reached via partner. Promo=STUDENT15; Phone:+9...
1,user1@example.com,Northwind,Engineer,Mysuru,Education,Reached via email. Promo=STUDENT15; Phone:+91-...
2,user2@example.com,Fabrikam,Student,Pune,Finance,Reached via partner. Promo=STUDENT15; Phone:+9...
3,user3@example.com,Fabrikam,Data Analyst,Pune,Finance,Reached via email. Promo=NA; Phone:+91-7059780...
4,user4@example.com,Contoso,Engineer,Hyderabad,Finance,Reached via partner. Promo=NA; Phone:+91-97425...

In [21]:
attendees_df["notes"][0]

'Reached via partner. Promo=STUDENT15; Phone:+91-7564409423; UTM=utm_source=email&utm_campaign=Q1_ML'

In [12]:
registrations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421 entries, 0 to 420
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reg_id          421 non-null    object
 1   event_id        421 non-null    object
 2   attendee_email  421 non-null    object
 3   reg_timestamp   421 non-null    object
 4   payment_status  421 non-null    object
 5   ticket_type     421 non-null    object
dtypes: object(6)
memory usage: 19.9+ KB

In [13]:
pricing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_id       12 non-null     object
 1   base_price     12 non-null     int64
 2   discount_code  11 non-null     object
 3   discount_pct   12 non-null     int64
 4   currency       12 non-null     object
dtypes: int64(2), object(3)
memory usage: 612.0+ bytes

In [14]:
events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   event_id             12 non-null     object
 1   topic                12 non-null     object
 2   city                 12 non-null     object
 3   venue_capacity       12 non-null     int64
 4   scheduled_date_time  12 non-null     object
 5   instructor_id        12 non-null     object
dtypes: int64(1), object(5)
memory usage: 708.0+ bytes

In [15]:
channels_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event_id     36 non-null     object
 1   channel      36 non-null     object
 2   spend        36 non-null     int64
 3   impressions  36 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.3+ KB

In [16]:
pricing_df.isna().sum()

event_id         0
base_price       0
discount_code    1
discount_pct     0
currency         0
dtype: int64

In [17]:
pricing_df.fillna('NA', inplace = True)

In [18]:
pricing_df.isna().sum()

event_id         0
base_price       0
discount_code    0
discount_pct     0
currency         0
dtype: int64

In [23]:
attendees_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   attendee_email  58 non-null     object
 1   company         58 non-null     object
 2   role            58 non-null     object
 3   city            58 non-null     object
 4   industry        58 non-null     object
 5   notes           58 non-null     object
dtypes: object(6)
memory usage: 2.8+ KB

Merging Events & Pricing

In [19]:
event_pricing = pd.merge(events_df, pricing_df, on='event_id', how="inner")

In [20]:
event_pricing.head()

,event_id,topic,city,venue_capacity,scheduled_date_time,instructor_id,base_price,discount_code,discount_pct,currency
0,E001,Python OOP,Bengaluru,50,2026-01-13 10:00,I001,3000,STUDENT15,15,INR
1,E002,Data Wrangling,Bengaluru,30,2026-01-16 14:00,I001,3000,EARLY10,10,INR
2,E003,Python OOP,Bengaluru,40,2026-01-19 10:00,I003,3000,NY25,25,INR
3,E004,Python OOP,Mysuru,60,2026-01-22 10:00,I002,3000,NY25,25,INR
4,E005,Machine Learning Essentials,Bengaluru,40,2026-01-25 14:00,I002,2000,NA,0,INR

In [24]:
registrations_attendees = pd.merge(registrations_df,attendees_df, on="attendee_email", how="inner")

In [25]:
registrations_attendees.head()

,reg_id,event_id,attendee_email,reg_timestamp,payment_status,ticket_type,company,role,city,industry,notes
0,RE001000,E001,user0@example.com,2025-12-31 10:00,paid,earlybird,Contoso,Student,Pune,IT,Reached via partner. Promo=STUDENT15; Phone:+9...
1,RE001001,E001,user1@example.com,2025-12-18 10:00,cancelled,standard,Northwind,Engineer,Mysuru,Education,Reached via email. Promo=STUDENT15; Phone:+91-...
2,RE001002,E001,user2@example.com,2025-12-23 10:00,pending,student,Fabrikam,Student,Pune,Finance,Reached via partner. Promo=STUDENT15; Phone:+9...
3,RE001003,E001,user3@example.com,2026-01-11 10:00,paid,student,Fabrikam,Data Analyst,Pune,Finance,Reached via email. Promo=NA; Phone:+91-7059780...
4,RE001004,E001,user4@example.com,2025-12-14 10:00,pending,standard,Contoso,Engineer,Hyderabad,Finance,Reached via partner. Promo=NA; Phone:+91-97425...

Calculating the Effective price

In [27]:
event_pricing["effective_price"] = event_pricing["base_price"] * (1 - (event_pricing["discount_pct"]/100))

In [28]:
event_pricing.head()

,event_id,topic,city,venue_capacity,scheduled_date_time,instructor_id,base_price,discount_code,discount_pct,currency,effective_price
0,E001,Python OOP,Bengaluru,50,2026-01-13 10:00,I001,3000,STUDENT15,15,INR,2550.0
1,E002,Data Wrangling,Bengaluru,30,2026-01-16 14:00,I001,3000,EARLY10,10,INR,2700.0
2,E003,Python OOP,Bengaluru,40,2026-01-19 10:00,I003,3000,NY25,25,INR,2250.0
3,E004,Python OOP,Mysuru,60,2026-01-22 10:00,I002,3000,NY25,25,INR,2250.0
4,E005,Machine Learning Essentials,Bengaluru,40,2026-01-25 14:00,I002,2000,NA,0,INR,2000.0

Converting datetime types

In [29]:
event_pricing["scheduled_date_time"] = pd.to_datetime(event_pricing["scheduled_date_time"])

In [30]:
event_pricing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   event_id             12 non-null     object
 1   topic                12 non-null     object
 2   city                 12 non-null     object
 3   venue_capacity       12 non-null     int64
 4   scheduled_date_time  12 non-null     datetime64[ns]
 5   instructor_id        12 non-null     object
 6   base_price           12 non-null     int64
 7   discount_code        12 non-null     object
 8   discount_pct         12 non-null     int64
 9   currency             12 non-null     object
 10  effective_price      12 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 1.2+ KB

In [31]:
registrations_attendees["reg_timestamp"] = pd.to_datetime(registrations_attendees["reg_timestamp"])

In [32]:
registrations_attendees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421 entries, 0 to 420
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reg_id          421 non-null    object
 1   event_id        421 non-null    object
 2   attendee_email  421 non-null    object
 3   reg_timestamp   421 non-null    datetime64[ns]
 4   payment_status  421 non-null    object
 5   ticket_type     421 non-null    object
 6   company         421 non-null    object
 7   role            421 non-null    object
 8   city            421 non-null    object
 9   industry        421 non-null    object
 10  notes           421 non-null    object
dtypes: datetime64[ns](1), object(10)
memory usage: 36.3+ KB

How many unique values are there in few categorical columns

In [33]:
registrations_attendees['role'].nunique()

4

In [34]:
registrations_attendees['industry'].nunique()

4

We will represent the categorical values as a category dtype for memory efficiency

In [37]:
columns_to_convert = ['payment_status', 'ticket_type','city','role','industry']
for col in columns_to_convert:
    registrations_attendees[col] = registrations_attendees[col].astype('category')

In [38]:
registrations_attendees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421 entries, 0 to 420
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reg_id          421 non-null    object
 1   event_id        421 non-null    object
 2   attendee_email  421 non-null    object
 3   reg_timestamp   421 non-null    datetime64[ns]
 4   payment_status  421 non-null    category
 5   ticket_type     421 non-null    category
 6   company         421 non-null    object
 7   role            421 non-null    category
 8   city            421 non-null    category
 9   industry        421 non-null    category
 10  notes           421 non-null    object
dtypes: category(5), datetime64[ns](1), object(5)
memory usage: 22.8+ KB

Do the same in event_pricing

In [39]:
event_pricing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   event_id             12 non-null     object
 1   topic                12 non-null     object
 2   city                 12 non-null     object
 3   venue_capacity       12 non-null     int64
 4   scheduled_date_time  12 non-null     datetime64[ns]
 5   instructor_id        12 non-null     object
 6   base_price           12 non-null     int64
 7   discount_code        12 non-null     object
 8   discount_pct         12 non-null     int64
 9   currency             12 non-null     object
 10  effective_price      12 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(6)
memory usage: 1.2+ KB

In [40]:
event_pricing['topic'].nunique()

3

In [41]:
columns_to_convert = ['city','topic']
for col in columns_to_convert:
    event_pricing[col] = event_pricing[col].astype('category')

In [42]:
event_pricing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   event_id             12 non-null     object
 1   topic                12 non-null     category
 2   city                 12 non-null     category
 3   venue_capacity       12 non-null     int64
 4   scheduled_date_time  12 non-null     datetime64[ns]
 5   instructor_id        12 non-null     object
 6   base_price           12 non-null     int64
 7   discount_code        12 non-null     object
 8   discount_pct         12 non-null     int64
 9   currency             12 non-null     object
 10  effective_price      12 non-null     float64
dtypes: category(2), datetime64[ns](1), float64(1), int64(3), object(4)
memory usage: 1.3+ KB