## First Exploring Pandas

In [1]:
d1 = {
"names": ["vishwas","arjun","ramya","John","Krishna"],
"city": ["Bangalore","mumbai","pune",None,"Kolkata"]
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(d1)

### Data Wrangling
Is a process of :
1. Collecting the Raw data
2. Cleaning the messy data
3. Transforming the data into usable format & structure
4. Enhancing data for analysis

### Information about dataframe

In [4]:
df.head()

     names       city
0  vishwas  Bangalore
1    arjun     mumbai
2    ramya       pune
3     John       None
4  Krishna    Kolkata

In [5]:
df.isna().sum()

names    0
city     1
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   names   5 non-null      object
 1   city    4 non-null      object
dtypes: object(2)
memory usage: 212.0+ bytes

### Adding Columns to a Dataframe

In [7]:
df['salary'] = [25000,45000,75000,90000,10000]

In [8]:
print(df)

     names       city  salary
0  vishwas  Bangalore   25000
1    arjun     mumbai   45000
2    ramya       pune   75000
3     John       None   90000
4  Krishna    Kolkata   10000

In [9]:
ages = [25,21,19,35,10]
df.insert(loc=1, column="age", value=ages)
print(df)

     names  age       city  salary
0  vishwas   25  Bangalore   25000
1    arjun   21     mumbai   45000
2    ramya   19       pune   75000
3     John   35       None   90000
4  Krishna   10    Kolkata   10000

### Handling missing values

In [10]:
d2 = {
    "col1":[None,1,2,3],
    "col2":[1,None,None,3],
    "col3":[1,2,None,20]
}
df1 = pd.DataFrame(d2)
print(df1.isna().sum())
print(df1)
df2 = df1.dropna()
print(df1)
df2.isna().sum()
print(df2)

col1    1
col2    2
col3    1
dtype: int64
   col1  col2  col3
0   NaN   1.0   1.0
1   1.0   NaN   2.0
2   2.0   NaN   NaN
3   3.0   3.0  20.0
   col1  col2  col3
0   NaN   1.0   1.0
1   1.0   NaN   2.0
2   2.0   NaN   NaN
3   3.0   3.0  20.0
   col1  col2  col3
3   3.0   3.0  20.0

In [11]:
df["city"].fillna("Unkown", inplace=True)

C:\Users\VishwasKSingh\AppData\Local\Temp\ipykernel_5996\1583701482.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["city"].fillna("Unkown", inplace=True)

In [12]:
print(df)

     names  age       city  salary
0  vishwas   25  Bangalore   25000
1    arjun   21     mumbai   45000
2    ramya   19       pune   75000
3     John   35     Unkown   90000
4  Krishna   10    Kolkata   10000

### Adding new Rows of data

In [21]:
new_row = ["Cady", 27, "Chandigarh", 23000]
df.loc[len(df)] = new_row
print(df)

     names  age        city   salary
0  vishwas   25   Bangalore  25000.0
1    arjun   21      mumbai  45000.0
2    ramya   19        pune  75000.0
3     John   35      Unkown  90000.0
4  Krishna   10     Kolkata  10000.0
5     Cady   27  Chandigarh  23000.0
6   Balram   45     Kolkata  90000.0
7     Jane   23     Kolkata  90000.0
8    Jugnu   46     Kolkata   8000.0
9     Cady   27  Chandigarh  23000.0

In [14]:
new_rows = [
    {"names": "Balram", "age": 45,"city":"Kolkata", "salary":90000},
    {"names": "Jane", "age": 23,"city":"Kolkata", "salary":90000},
    {"names": "Jugnu", "age": 46,"city":"Kolkata", "salary":8000}
]

new_df = pd.DataFrame(new_rows)

df = pd.concat([df, new_df], ignore_index=True)
print(df)

     names  age        city  salary
0  vishwas   25   Bangalore   25000
1    arjun   21      mumbai   45000
2    ramya   19        pune   75000
3     John   35      Unkown   90000
4  Krishna   10     Kolkata   10000
5     Cady   27  Chandigarh   23000
6   Balram   45     Kolkata   90000
7     Jane   23     Kolkata   90000
8    Jugnu   46     Kolkata    8000

### Converting dtypes

In [18]:
df["salary"] = df["salary"].astype(float)

In [22]:
print(df)

     names  age        city   salary
0  vishwas   25   Bangalore  25000.0
1    arjun   21      mumbai  45000.0
2    ramya   19        pune  75000.0
3     John   35      Unkown  90000.0
4  Krishna   10     Kolkata  10000.0
5     Cady   27  Chandigarh  23000.0
6   Balram   45     Kolkata  90000.0
7     Jane   23     Kolkata  90000.0
8    Jugnu   46     Kolkata   8000.0
9     Cady   27  Chandigarh  23000.0

### Removing Duplicates

In [23]:
df.duplicated().sum()

np.int64(1)

In [24]:
df.drop_duplicates(inplace=True)

In [25]:
print(df)

     names  age        city   salary
0  vishwas   25   Bangalore  25000.0
1    arjun   21      mumbai  45000.0
2    ramya   19        pune  75000.0
3     John   35      Unkown  90000.0
4  Krishna   10     Kolkata  10000.0
5     Cady   27  Chandigarh  23000.0
6   Balram   45     Kolkata  90000.0
7     Jane   23     Kolkata  90000.0
8    Jugnu   46     Kolkata   8000.0

### Renaming the columns

In [26]:
df.columns = df.columns.str.upper()
print(df)

     NAMES  AGE        CITY   SALARY
0  vishwas   25   Bangalore  25000.0
1    arjun   21      mumbai  45000.0
2    ramya   19        pune  75000.0
3     John   35      Unkown  90000.0
4  Krishna   10     Kolkata  10000.0
5     Cady   27  Chandigarh  23000.0
6   Balram   45     Kolkata  90000.0
7     Jane   23     Kolkata  90000.0
8    Jugnu   46     Kolkata   8000.0

### Filtering data to new dataframe

In [28]:
new_df = df[df["AGE"] > 21]

In [29]:
print(new_df)

     NAMES  AGE        CITY   SALARY
0  vishwas   25   Bangalore  25000.0
3     John   35      Unkown  90000.0
5     Cady   27  Chandigarh  23000.0
6   Balram   45     Kolkata  90000.0
7     Jane   23     Kolkata  90000.0
8    Jugnu   46     Kolkata   8000.0

In [30]:
new_df = df.loc[df["CITY"] == "Unkown", ["NAMES","AGE"]]
print(new_df)

  NAMES  AGE
3  John   35

### Creating New Columns

In [31]:
df["age_group"] = df["AGE"].apply(
    lambda x: "Young" if x < 25 else "Adult"
)
print(df)

     NAMES  AGE        CITY   SALARY age_group
0  vishwas   25   Bangalore  25000.0     Adult
1    arjun   21      mumbai  45000.0     Young
2    ramya   19        pune  75000.0     Young
3     John   35      Unkown  90000.0     Adult
4  Krishna   10     Kolkata  10000.0     Young
5     Cady   27  Chandigarh  23000.0     Adult
6   Balram   45     Kolkata  90000.0     Adult
7     Jane   23     Kolkata  90000.0     Young
8    Jugnu   46     Kolkata   8000.0     Adult

In [33]:
df["salary_bonus"] = df["SALARY"] * 0.1
print(df)

     NAMES  AGE        CITY   SALARY age_group  salary_bonus
0  vishwas   25   Bangalore  25000.0     Adult        2500.0
1    arjun   21      mumbai  45000.0     Young        4500.0
2    ramya   19        pune  75000.0     Young        7500.0
3     John   35      Unkown  90000.0     Adult        9000.0
4  Krishna   10     Kolkata  10000.0     Young        1000.0
5     Cady   27  Chandigarh  23000.0     Adult        2300.0
6   Balram   45     Kolkata  90000.0     Adult        9000.0
7     Jane   23     Kolkata  90000.0     Young        9000.0
8    Jugnu   46     Kolkata   8000.0     Adult         800.0

### Grouping of Data

In [35]:
# average salary based on city
df.groupby('CITY')['SALARY'].mean()

CITY
Bangalore     25000.0
Chandigarh    23000.0
Kolkata       49500.0
Unkown        90000.0
mumbai        45000.0
pune          75000.0
Name: SALARY, dtype: float64

In [37]:
df.groupby('CITY').agg({
    'salary_bonus': 'sum',
    'SALARY': 'mean',
    'AGE':'mean'
})

            salary_bonus   SALARY   AGE
CITY
Bangalore         2500.0  25000.0  25.0
Chandigarh        2300.0  23000.0  27.0
Kolkata          19800.0  49500.0  31.0
Unkown            9000.0  90000.0  35.0
mumbai            4500.0  45000.0  21.0
pune              7500.0  75000.0  19.0

### Merging or Joining of data

In [38]:
d3 = {
    "NAMES": ["vishwas","arjun","ramya","John","Krishna","Cady","Balram","Jane","Jugnu"],
    "DEPARTMENT": ["IT","SALES","IT","SALES","FINANCE","FINANCE","SALES","SALES","IT"]
}

new_df = pd.DataFrame(d3)
df_joined = pd.merge(df,new_df, on="NAMES", how="inner") # left,right,outer
print(df_joined)

     NAMES  AGE        CITY   SALARY age_group  salary_bonus DEPARTMENT
0  vishwas   25   Bangalore  25000.0     Adult        2500.0         IT
1    arjun   21      mumbai  45000.0     Young        4500.0      SALES
2    ramya   19        pune  75000.0     Young        7500.0         IT
3     John   35      Unkown  90000.0     Adult        9000.0      SALES
4  Krishna   10     Kolkata  10000.0     Young        1000.0    FINANCE
5     Cady   27  Chandigarh  23000.0     Adult        2300.0    FINANCE
6   Balram   45     Kolkata  90000.0     Adult        9000.0      SALES
7     Jane   23     Kolkata  90000.0     Young        9000.0      SALES
8    Jugnu   46     Kolkata   8000.0     Adult         800.0         IT

In [42]:
df_pivot = df_joined.pivot_table(
    values = "salary_bonus",
    index = "DEPARTMENT",
    columns="CITY",
    aggfunc = "sum"
)

df_pivot.fillna(0, inplace=True)
#print(df_pivot)
df_pivot.head()

CITY        Bangalore  Chandigarh  Kolkata  Unkown  mumbai    pune
DEPARTMENT
FINANCE           0.0      2300.0   1000.0     0.0     0.0     0.0
IT             2500.0         0.0    800.0     0.0     0.0  7500.0
SALES             0.0         0.0  18000.0  9000.0  4500.0     0.0

In [ ]:
assert df_joined['AGE'].max() < 60

### Saving DataFrames

In [45]:
df_joined.to_csv("employee_data.csv", index=False)

In [46]:
from sqlalchemy import create_engine

In [48]:
engine = create_engine("sqlite:///employee_data.db")

In [49]:
df_joined.to_sql(
    name="employees",
    con=engine,
    if_exists="replace",
    index=False
)

9

In [50]:
df_db = pd.read_sql("SELECT * FROM employees", engine)
print(df_db)

     NAMES  AGE        CITY   SALARY age_group  salary_bonus DEPARTMENT
0  vishwas   25   Bangalore  25000.0     Adult        2500.0         IT
1    arjun   21      mumbai  45000.0     Young        4500.0      SALES
2    ramya   19        pune  75000.0     Young        7500.0         IT
3     John   35      Unkown  90000.0     Adult        9000.0      SALES
4  Krishna   10     Kolkata  10000.0     Young        1000.0    FINANCE
5     Cady   27  Chandigarh  23000.0     Adult        2300.0    FINANCE
6   Balram   45     Kolkata  90000.0     Adult        9000.0      SALES
7     Jane   23     Kolkata  90000.0     Young        9000.0      SALES
8    Jugnu   46     Kolkata   8000.0     Adult         800.0         IT

In [51]:
engine.dispose()

### Connecting with a context manager

In [52]:
from sqlalchemy import create_engine, Integer, String, Numeric
engine = create_engine("sqlite:///employee_data.db")

with engine.begin() as conn:
    df_joined.to_sql(
        "employees",
        con=conn,
        if_exists = "replace",
        index=False,
        dtype={
            "NAMES":String(100),
            "AGE": Integer,
            "CITY": String(100),
            "SALARY": Numeric(8,2),
            "age_group":String(100),
            "salary_bonus":Numeric(8,2),
            "DEPARTMENT":String(100)
        }
    )

In [53]:
df_db = pd.read_sql("SELECT * FROM employees", engine)
print(df_db)

     NAMES  AGE        CITY  SALARY age_group  salary_bonus DEPARTMENT
0  vishwas   25   Bangalore   25000     Adult          2500         IT
1    arjun   21      mumbai   45000     Young          4500      SALES
2    ramya   19        pune   75000     Young          7500         IT
3     John   35      Unkown   90000     Adult          9000      SALES
4  Krishna   10     Kolkata   10000     Young          1000    FINANCE
5     Cady   27  Chandigarh   23000     Adult          2300    FINANCE
6   Balram   45     Kolkata   90000     Adult          9000      SALES
7     Jane   23     Kolkata   90000     Young          9000      SALES
8    Jugnu   46     Kolkata    8000     Adult           800         IT

### Reading from a public google sheet

In [54]:
sheet_id = "1bJrUAydrB7CY1OJZkalDuKQ8TAnMvthMCA0s9w3ObeM"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"

hire_df = pd.read_csv(url)
hire_df.head()

,Candidate Name,Gender,Age,Education Level,Experience (years),Applied Position,Interview Date,Interviewer,Status,Current Salary,Salary Expectation,Salary Offered
0,John Smith,Male,28,Bachelor's,4,Software Eng.,2023-08-10,Sarah Brown,Offer,"$205,428.00","$305,428.00","$505,428.00"
1,Emily Johnson,Female,24,Master's,2,Data Analyst,2023-08-12,Mark Davis,In Progress,"$201,869.00","$301,869.00",NaN
2,Michael Lee,Male,32,Bachelor's,8,Project Manager,2023-08-15,Lisa Green,Rejected,"$292,407.00","$392,407.00",NaN
3,Jessica Wang,Female,27,Bachelor's,3,UX Designer,2023-08-14,Chris White,Offer,"$98,980.00","$122,350.00","$222,350.00"
4,David Miller,Male,30,Master's,6,Data Scientist,2023-08-13,Emily Black,On Hold,"$347,997.00","$447,997.00",NaN

In [57]:
attendees_df = pd.read_json(r"C:\Users\VishwasKSingh\Workspace\kantar-workspace-1\my_project\data\attendees.json")
attendees_df.head(3)

,attendee_email,company,role,city,industry,notes
0,user0@example.com,Contoso,Student,Pune,IT,Reached via partner. Promo=STUDENT15; Phone:+9...
1,user1@example.com,Northwind,Engineer,Mysuru,Education,Reached via email. Promo=STUDENT15; Phone:+91-...
2,user2@example.com,Fabrikam,Student,Pune,Finance,Reached via partner. Promo=STUDENT15; Phone:+9...